### ISSUE TITLE
Returning last inserted id

### ISSUE THREAD

**Issue by vladfaust** [will/crystal-pg#112]
Refer to https://github.com/will/crystal-pg/blob/800540888edf4012d2fdaba5d508665b462700dc/src/pg/statement.cr#L39

But there is an option with `RETURNING`; maybe this could be implemented?

**Comment by will** [comment]
I'm not sure how the driver here would know to add `RETURNING` automatically, because not every statement is an insert, and not every id column is necessarily called `"id"`

Also, it looks like it's used in this struct https://github.com/crystal-lang/crystal-db/blob/385cf70a8a5d41374cce988168e82495743ee459/src/db.cr#L80 But I often have tables where the ID is not an Int64, often they're UUIDs or something else, so I'm not sure it's generalizable at all. This might be something that comes from mysql or something?

**Comment by vladfaust** [comment]
@will I agree that `last_insert_id : Int64` is idiomatically wrong. Maybe it worths opening an issue in [crystal-db](https://github.com/crystal-lang/crystal-db)? Like, change to `Int64 | String`?

I'm not sure, but aren't you able to check whether is `RETURNING` present in a query? If yes, maybe parse the first value... It add some covenants, though.

**Comment by vladfaust** [comment]
`rows_affected` equals to 0 too.

**Comment by nicferrier** [comment]
I can't even get RETURNING to work, the code gets tangled up. It looks like support was there in the frame.cr code once (DataRow) but it doesn't work now.

**Comment by vladfaust** [comment]
So, could anyone make `RETURNING` work?

**Comment by RX14** [comment]
`RETURNING` has always worked for me

**Comment by vladfaust** [comment]
Hm, yes. It works if doing `db.query("INSERT ... RETURNING *")`... So the issue regrads to `ExecResult`.

**Comment by RX14** [comment]
What?

**Comment by RX14** [comment]
Thats just how postgres works. `ExecResult` is useless for postgres. What if your primary key wasn't an `Int64`?

**Comment by vladfaust** [comment]
Yep. Closing this one then.

**Comment by waghanza** [comment]
Does `RETURNING` works for `exec` ? or only for `query` ?
