### ISSUE TITLE
Is it possible to have a multiple statement query?

### ISSUE THREAD

**Issue by da99** [will/crystal-pg#139]
The following SQL fails using the `.query` methods because it has multiple statements:

     SET LOCAL my.val = 'abc';
     SELECT current_setting('my.val') as my_val, 'aa' as now_;
 
Is there a way to execute this query? Maybe as an unprepared statement?

**Comment by will** [comment]
Postgres has two protocols for executing queries. One ([extended query](https://www.postgresql.org/docs/current/static/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY)) allows parameters and other advanced features, but only one statement at a time. The other ([simple query](https://www.postgresql.org/docs/current/static/protocol-flow.html#id-1.10.5.7.4)) allows multiple statements, but is very basic. 

In order to prevent some problems, we only return results using the extended query protocol. We do support the simple one also (https://github.com/will/crystal-pg/blob/master/src/pg/connection.cr#L29), but don't return results for that, it's intended for creating tables or other DDL. 

I think the best way forward is to start a transaction and issue the two statements separately.

**Comment by da99** [comment]
Thanks. That cleared a lot of things up for me.
