### ISSUE TITLE
Are UUID's supposed to work or am I doing something wrong?

### ISSUE THREAD

**Issue by horrendo** [will/crystal-pg#142]
(Sorry if this is a dumb question)

```bash
Steve:pg_csvlog stbaldwin$ cat t.cr
require "db"
require "pg"
require "uuid"

uri = URI.new
uri.scheme = "postgres"
uri.user = ENV["PGUSER"]
uri.password = ENV["PGPASSWORD"]?
uri.host = ENV["PGHOST"]?
uri.port = ENV["PGPORT"]?.try &.to_i
uri.path = "/" + ENV["PGDATABASE"]

DB.open uri do |db|
  db.query "select gen_random_uuid()" do |rows|
    rows.each do
      u = rows.read(UUID)
      puts "Retrieved #{u}"
    end
  end
end
Steve:pg_csvlog stbaldwin$ crystal t.cr
PG::ResultSet#read returned a String. A UUID was expected. (Exception)
  from lib/db/src/db/result_set.cr:0:9 in 'read'
  from t.cr:16:11 in '__crystal_main'
  from /usr/local/Cellar/crystal-lang/0.24.2_1/src/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/local/Cellar/crystal-lang/0.24.2_1/src/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/local/Cellar/crystal-lang/0.24.2_1/src/crystal/main.cr:101:7 in 'main'
  from /usr/local/Cellar/crystal-lang/0.24.2_1/src/crystal/main.cr:135:3 in 'main'
Steve:pg_csvlog stbaldwin$ psql
psql (10.4)
Type "help" for help.

log=# 
```
As you can see, this is connecting to pg 10.4.

If I change the .read(UUID) to .read(String) it works.

**Comment by will** [comment]
UUID was added relatively recently to crystal (v0.24.1), and [the decoder](https://github.com/will/crystal-pg/blob/master/src/pg/decoder.cr#L241-L273) in crystal-pg predates that, so you're correct that it returns a string instead of the uuid struct. 

It might be useful to change the decoder, but that would be a breaking change. I haven't thought through it as to which is better. 

In the mean time, in your program that uses crystal-pg, it is possible to make your own decoder and register it in place of the built-in decoder.

**Comment by horrendo** [comment]
Thanks for the feedback. I'm fine with the way it is. I just saw that UUID was a supported data type and presumed it would result in a crystal uuid object. I'm a crystal noob so thought I may have been doing something wrong.
