### ISSUE TITLE
Implement crystal-db

### ISSUE THREAD

**Issue by asterite** [will/crystal-pg#59]
[crystal-db](https://github.com/crystal-lang/crystal-db) provides a unified interface for dealing with databases. Right now we have drivers for [sqlite3](https://github.com/crystal-lang/crystal-sqlite3) and [mysql](https://github.com/crystal-lang/crystal-mysql), and it would be great to have a postgres driver.

@will I think the main worry you had about adopting this is to loose some postgres-only features, or being able to deal directly with the connection without going through the DB interface. This is currently possible, a DB connection has a [with_connection](https://github.com/crystal-lang/crystal-db/blob/d7fdf1eada852ea084b7b9786e149094ec5270e0/src/db/database.cr#L79) method that yields the underlying connection for this. But before that...

I have a partial implementation of this [here](https://github.com/asterite/crystal-pg/tree/feature/db), but I didn't maintain it for some time and your repo continued evolving so I probably need to rebase.

Question: would you be fine with merging a PR that contains this functionality? This will of course be backwards incompatible. Otherwise we can simply have a driver in some other repository, maybe `crystal-lang/crystal-pg`. What do you think?

**Comment by will** [comment]
More than anything I think we should keep it in one shard to avoid confusion, and if this is something that everyone wants, it is more important to keep the community together than any of my individual concerns.

My rough concerns are:
  * yes the postgres-only features: listen/notify, COPY (though I haven't added support for that yet)
  * similarly more advanced data types. I'm not sure from reading the crystal-db stuff how you can read out complicated types like the geo stuff or arrays, etc
  * I want to make sure we don't give up the ability to stream result sets.
  *  while pooling isn't in crystal-db yet, it's important to have a proc of statements that runs on new connections to set up appropriate connection state. This is a small concern since the pool isn't written yet, but it is broken in the go language.

I'm confused though what makes adding a new interface a backwards incompatible change.

**Comment by asterite** [comment]
* Reading a custom type is easy: the driver defines a `read(type : T.class)`. For example pg would define a `read(point : Geo::Point.class)` and you'd do `rs.read(Geo::Point)`.
* Streaming results is the first way provided by crystal-db, so we are good there :-)
* crystal-db has now a basic connection pool, though it probably needs a bit more work. We can definitely work together to have an API that doesn't have the problem that Go has
* By backwards-incompatible I mean that `PG.connect` will disappear, as well as every method to get data from the database. The only way would be the interface provided by `crystal-db` (though of course you could keep the internal implementation with your current API available, if that's what you want, but I don't know if it makes sense to do that)

In any case, I'll try to prepare a PR this week and send it, it will be much easier to discuss this with a concrete implementation :-)

**Comment by fridgerator** [comment]
this has been accomplished, correct?

**Comment by will** [comment]
Yeah #60 implemented it. Thanks
